import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { withAuth } from "@/lib/api-auth";

export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {
  return withAuth(async () => {
    const { id } = await params;
    const stock = await prisma.stock.findUnique({
      where: { id: parseInt(id) },
      include: { product: true },
    });
    if (!stock) {
      return NextResponse.json({ error: "Not found" }, { status: 404 });
    }
    return NextResponse.json(stock);
  });
}

export async function PUT(request: Request, { params }: { params: Promise<{ id: string }> }) {
  return withAuth(async () => {
    try {
      const { id } = await params;
      const stockId = parseInt(id);

      const existingStock = await prisma.stock.findUnique({
        where: { id: stockId },
      });
      if (!existingStock) {
        return NextResponse.json({ error: "Not found" }, { status: 404 });
      }
      if (existingStock.purchaseId) {
        return NextResponse.json(
          { error: "Cannot edit stock that was auto-generated by a Purchase. Please edit the Purchase record." },
          { status: 400 }
        );
      }

      const data = await request.json();
      const stock = await prisma.stock.update({
        where: { id: stockId },
        data: {
          batchNo: data.batchNo,
          productId: data.productId ? parseInt(data.productId) : null,
          invoiceNo: data.invoiceNo,
          quantity: data.quantity != null ? Number(data.quantity) : undefined,
          productCost: data.productCost != null ? Number(data.productCost) : undefined,
        },
      });
      return NextResponse.json(stock);
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : "Failed to update";
      return NextResponse.json({ error: message }, { status: 400 });
    }
  }, "Owner");
}

export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string }> }) {
  return withAuth(async () => {
    const { id } = await params;
    const stockId = parseInt(id);

    const existingStock = await prisma.stock.findUnique({
      where: { id: stockId },
    });
    if (!existingStock) {
      return NextResponse.json({ error: "Not found" }, { status: 404 });
    }
    if (existingStock.purchaseId) {
      return NextResponse.json(
        { error: "Cannot delete stock that was auto-generated by a Purchase. Please delete the Purchase record." },
        { status: 400 }
      );
    }

    await prisma.stock.update({ where: { id: stockId }, data: { isDeleted: true } });
    return NextResponse.json({ success: true });
  }, "Owner");
}
